name: Build and Test

'on':
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4
            -
                name: Build
                shell: bash
                run: make
            -
                name: Run test suite
                shell: bash
                run: bash tests/run.sh
